#!/usr/bin/env bash

###
# SET OPENAI KEY
###
OPENAI_KEY_PATH="$HOME/Documents/denv/bin/aider.env"
if [ -f $OPENAI_KEY_PATH ]; then
    source $OPENAI_KEY_PATH
fi
if [ -z "$OPENAI_API_KEY" ]; then
    echo "OPENAI_API_KEY not set. Set in aider.env."
    exit 1
fi

###
# USE LOCAL CHAT HISTORY FILE IF PRESENT, OTHERWISE USE GLOBAL
###
LOCAL_HISTORY="$PWD/.aider.chat.history.md"
GLOBAL_HISTORY="$HOME/Documents/denv/dotfiles/ai/aider-global-history.md"
if [ -f "$LOCAL_HISTORY" ]; then
    echo "use aider local history file"
    export AIDER_CHAT_HISTORY_FILE="$LOCAL_HISTORY"
else
    echo "use aider global history file"
    export AIDER_CHAT_HISTORY_FILE="$GLOBAL_HISTORY"
fi

###
# RUN AIDER
###
aider "$@"
