#!/usr/bin/env python

from random import randint, sample

key = sample(["F", "C", "G"], 1)[0]
chords = sample(["I", "ii", "iii", "IV", "V", "vi", "vii°"], randint(2, 4))
melody = sample([1, 3, 4, 5, 7], randint(2, 5))

print("\n🥁 https://www.rhythmrandomizer.com")
print(f"\n🔑 KEY: {key}")
print(f"\n🎼 CHORDS: {chords}")
print(f"\n🎶 MELODY {melody}")

# for chord, quality in zip(sample([1, 2, 3, 4, 5, 6, 7], 4), sample(["°", "-", "M", "+", ], 4)):
#     print(chord, quality)

