#!/usr/bin/env python

from webbrowser import open_new_tab

# NEWS
open_new_tab("https://mail.google.com")
open_new_tab("https://www.semafor.com")
open_new_tab("https://news.kagi.com/world/latest")
open_new_tab("https://news.kagi.com/business/latest")

# SW
open_new_tab("https://news.ycombinator.com/")
open_new_tab("https://www.youtube.com/feed/subscriptions")
open_new_tab("https://www.youtube.com/playlist?list=WL")

# ZA
open_new_tab("https://news.kagi.com/onthisday/latest")
open_new_tab("https://marginalrevolution.com/")
open_new_tab("https://news.kagi.com/sports/latest")
open_new_tab("https://plaintextsports.com/mlb/2026/teams/philadelphia-phillies")
