#!/usr/bin/env bash

###
# DNS
###

# doggo zachvalenta.com --time
# doggo liyasthomas.github.io --time
# doggo zjayv.github.io --time
# doggo zjayv.com --time

###
# HTTP: STATUS CODE PASS/FAIL
###

control_url="https://liyasthomas.github.io/"
control_status=$(curl -o /dev/null -s -w "%{http_code}" "$control_url")
control="$control_url,$control_status"
treatment_url="https://zjayv.github.io/"
treatment_status=$(curl -o /dev/null -s -w "%{http_code}" "$treatment_url")
treatment="$treatment_url,$treatment_status"
sites=($control $treatment)

for site in "${sites[@]}"; do
  if [[ "$(echo "$site" | cut -d ',' -f 2)" == "200" ]]; then
    bg="green"
    fg="$(pastel textcolor "$bg")"
    pastel paint "$fg" --on "$bg" "url: $(echo "$site" | cut -d ',' -f 1) status: $(echo "$site" | cut -d ',' -f 2)"
  else
    bg="red"
    fg="$(pastel textcolor "$bg")"
    pastel paint "$fg" --on "$bg" "url: $(echo "$site" | cut -d ',' -f 1) status: $(echo "$site" | cut -d ',' -f 2)"
  fi
done

###
# HTTP: DEBUG
###

# curl -I https://liyasthomas.github.io/
# curl -I https://zjayv.github.io/
