#!/usr/bin/env bash

OUTPUT_DIR="$HOME/Documents/denv/logs/sys-info"

procs --sortd mem | awk '{ print substr($0, 1, 100) }' | head -n 100 > $OUTPUT_DIR/"$(date +'%y%m%d_%H%M%S')_proc.txt"

cd ~/Documents/zv/
dust -ji -z 30MB -d 3 > $OUTPUT_DIR/"$(date +'%y%m%d_%H%M%S')_storage.txt"
